controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    rotor_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

rotor_velocity_controller:
  ros__parameters:
    joints:
      - joint_rotor_fl
      - joint_rotor_fr
      - joint_rotor_rl
      - joint_rotor_rr
      - joint_rotor_pusher
